### ISSUE TITLE
Error with balena-cam

### ISSUE THREAD

**Issue by wisehackermonkey** [edgeimpulse/balena-cam-tinyml#7]
# Important context: `I dont have a raspberry pi cam connected.` only a usb one. 
### model is: logitech webcam c920 

![image](https://user-images.githubusercontent.com/29699356/165371128-6ef9d7e3-cdd6-4477-949a-90057cd99fae.png)
---

# I'm having an issue with running the balena-cam container. it errors out with this message. 

![image](https://user-images.githubusercontent.com/29699356/165370024-87cc8921-4236-42d6-8c24-bee56223d9b6.png)
```bash
Restarting service 'balena-cam sha256:64ad977a474b929eb58bb71bd789932bb43d93e3a6c5ad241bf31e431f25f8f6'
 balena-cam  Traceback (most recent call last):
 balena-cam    File "/usr/src/app/server.py", line 7, in <module>
 balena-cam      from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack, RTCIceServer, RTCConfiguration
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/aiortc/__init__.py", line 2, in <module>
 balena-cam      from .mediastreams import (AudioStreamTrack,  # noqa
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/aiortc/mediastreams.py", line 7, in <module>
 balena-cam      from pyee import EventEmitter
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/pyee/__init__.py", line 34, in <module>
 balena-cam      from pyee.base import EventEmitter as EventEmitter
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/pyee/base.py", line 43
 balena-cam      self._events: Dict[
 balena-cam                  ^
 balena-cam  SyntaxError: invalid syntax
```

# Hardware used:
- raspberry pi 4 8gb 
- logitech webcam c920 (camera)

# Any thoughts?

**Comment by ramazanyich** [comment]
same here with Logitech USB webcam :(
